### ISSUE TITLE
Make dockerhub repo for hypertrace/hypertrace

### ISSUE THREAD

**Issue by adriancole** [hypertrace/hypertrace-service#27]
https://hub.docker.com/r/hypertrace/hypertrace-federated-service currently exists, but the docker image should be for hypertrace/hypertrace now. Usually, I would log in and replicate the setup just under a different name.

I don't have access to do this. @ravisingal @laxmanchekka do you?

**Comment by adriancole** [comment]
@ravisingal @laxmanchekka are either of you on this? Otherwise, if you want me to help fix, please grant me *Owner* access in DockerHub and I can give it a shot

**Comment by JBAhire** [comment]
This is done!
